name: Generate Examples

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  generate-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v22
      - uses: DeterminateSystems/magic-nix-cache-action@v14
      - uses: Swatinem/rust-cache@v2
      - run: nix develop --command make
      - run: nix develop --command bash examples/index.typ compile
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v5
      - uses: actions/deploy-pages@v4
